codecov:
  require_ci_to_pass: yes
coverage:
  status:
    patch: no
    project:
      default:
        target: 35%
        if_not_found: success
        if_ci_failed: error # success, failure, error, ignore
    changes: no
  precision: 2
  round: down
  range: 50..100
ignore:
  - "helm/**"
comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
